name: Build and Deploy Spring Boot App to Docker Hub and EC2
###
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    environment: MY_ENV

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build Spring Boot JAR
        run: |
          mvn clean package -DskipTests
          ls -l target

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/springboot-app-chroma:latest .

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/springboot-app-chroma:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment: MY_ENV
    steps:
      - name: Connect to EC2 and deploy new Docker image
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "Logging in to Docker Hub..."
            docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}

            echo "Pulling the latest Docker image..."
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/springboot-app-chroma:latest

            echo "Stopping old container if exists..."
            docker stop springboot-app || true
            docker rm springboot-app || true

            echo "Running new container on port 5000..."
            docker run -d --name springboot-app -p 5000:8080 \
              ${{ secrets.DOCKERHUB_USERNAME }}/springboot-app-chroma:latest

            echo "Deployment completed successfully!"
